# GitHub Pages Website Config File

theme: jekyll-theme-minimal
title: iAgoryNt's homepage
description: Bookmark this to keep an eye on my project updates!
logo: /Assets/logo.png
show_downloads: true

